version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_server
    restart: unless-stopped

    environment:
      POSTGRES_USER: 'Emerson'
      POSTGRES_PASSWORD: 'unifesspa'
      POSTGRES_DB: 'Academia'

  
    ports:
      - "5432:5432"
